### ISSUE TITLE
Can not support elixir version 1.1.0?

### ISSUE THREAD

**Issue by dcy** [antp/mailer#9]
*\* (Mix) You're trying to run :mailer on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.0.0
I change the mix.exs of mailer and timex, set elixir version to 1.1.0
and mix compile's error:
dcy@dcy-dcy:~/app/mailer$ mix compile

== Compilation error on file lib/date/datetime.ex ==
*\* (ArgumentError) Access is not a protocol, cannot derive Access for Timex.DateTime
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:591: Protocol.derive/5
    (stdlib) lists.erl:1336: :lists.foreach/2
    (elixir) lib/protocol.ex:579: Protocol.**derive**/3
    lib/date/datetime.ex:6: (module)

==> timex

**Comment by antp** [comment]
The problem is with the Timex library requiring Elixir 1.0.0.  You will need fork the library and ensure that it will run and pass its tests with Elixir 1.1.0.

I have run some tests to see if mailer will run on Elixir 1.1.0 but there seems to be some issues with some of the dependancies that need investigating.
